version: "3"

services:
  nuxt:
    image: node:14
    container_name: docker-nuxt
    restart: always
    working_dir: /var/www
    volumes:
      - "./:/var/www"
    ports:
      - "3000:3000"
    command: "yarn dev"
    environment:
      HOST: 0.0.0.0
